// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $add from "./routes/add.tsx";
import * as $index from "./routes/index.tsx";
import * as $AreaDeMensajes from "./islands/AreaDeMensajes.tsx";
import * as $FormularioContacto from "./islands/FormularioContacto.tsx";
import * as $ListaDeContactos from "./islands/ListaDeContactos.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/add.tsx": $add,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AreaDeMensajes.tsx": $AreaDeMensajes,
    "./islands/FormularioContacto.tsx": $FormularioContacto,
    "./islands/ListaDeContactos.tsx": $ListaDeContactos,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
